# Generated by Django 5.0.3 on 2024-03-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demon_slayer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='race',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
