# Generated by Django 5.0.3 on 2024-03-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demon_slayer_app', '0002_alter_demon_affiliation_alter_demon_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='affiliation'),
        ),
        migrations.AlterField(
            model_name='demon',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='demon',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='quote'),
        ),
        migrations.AlterField(
            model_name='demon',
            name='race',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='race'),
        ),
        migrations.AlterField(
            model_name='demon',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='skill'),
        ),
    ]
